### ISSUE TITLE
Key-based item uniqueness

### ISSUE THREAD

**Issue by gregsdennis** [json-schema-org/json-schema-vocabularies#22]
It may be handy to be able to specify key-based uniqueness within an array of items.

Given the schema

```json
{
  "type" : "array",
  "items" : {
    "type" : "object",
    "properties" : {
      "key" : { "type" : "string" },
      "value" : { "type" : "integer" }
    }
  },
  "uniqueItems" : true
}
```

the instance

```json
[ { "key" : 1, "value" : "value1" }, { "key" : 1, "value" : "value2" } ]
```
would pass.  However, the user may want this to fail as the value of the `key` property is repeated.

I propose a `uniquenessKey` (or similar) keyword that would allow the author to specify a pointer to an object property that should be unique among all items within the array.  This would update the above schema to

```json
{
  "type" : "array",
  "items" : {
    "type" : "object",
    "properties" : {
      "key" : { "type" : "string" },
      "value" : { "type" : "integer" }
    }
  },
  "uniquenessKey" : "#/key"
}
```

(The pointer would be resolved using the item in the array as the root.)

**Comment by handrews** [comment]
@gregsdennis Or we could just use Relative JSON Pointer which is designed specifically to solve this problem, is one of the specs we publish, and is used throughout JSON Hyper-Schema already.

**Comment by amitchone** [comment]
Hi all, I'd just like to mention that I'd be interested in this feature too! Not a difficult problem to solve for me with separate code, but nonetheless, if it was eventually included that would be great. 

Cheers,
Adam

**Comment by karenetheridge** [comment]
`isUniqueByProperty: <propertyname>`  and `isSortedByProperty: <propertyname>` would be great vocabularies to help pioneer a new vocabulary development process :)  count me in!

**Comment by gregsdennis** [comment]
@karenetheridge I prefer having a pointer to a property rather than just a property name.  This allows the key to be nested in the object somewhere.

**Comment by karenetheridge** [comment]
@gregsdennis Interesting. So in the basic case (an array of objects of strings), `"isUniqueByProperty": "mypropertyname"` would just be `"isUniqueByInsertBikeshedHere": "/mypropertyname"` instead. But we could make it even more generalized by not requiring an an array of objects, but an array of anything:

```
{
  "type": "array",
  "isUniqueByPath": "/0/foo/bar",
  "isSortedByPath": "/0/foo/bar",
  "items": {
    "type": "array",
    "items": {
      "type": "object",
      "requires": [ "foo" ],
      "properties: {
        "foo": {
          "type: "object",
          "requires": [ "bar" ],
          "properties": {
            "$comment": "this is used as the uniqueness/sorting key for the top level array",
            "bar": { "type": "string" }
          }
        }
      }
    }
  }
}
```

..or is that too complicated?

(edit: I'm having difficulty thinking of when a nested array might be useful though. I think you had the better idea.) :)

**Comment by gregsdennis** [comment]
That's what I'm thinking.  I'm not sure if it will be useful, either, but my experience is that _someone_ will want it.

**Comment by joaomcarlos** [comment]
If it doesn't exist, no one _can_ have it. Adoption is purely based on existing functionality. If its not available, then devs will implement it at application layer, which... helps no one.

You can apply the same thinking recursively all the way up and have JsonSchemas support only string types with zero extra validations... people that need those will implement at application level.

This is not some obscure functionality either, uniqueness of _things_ is a core concept of information passing objects. If JsonSchema is expressive enough to provide those and its support is widely adopted, then you don't need extra layers to provide that functionality anymore, which simplifies systems and improves robustness :)

Its more of a "want" than an "if": it **is** needed, just depends if anyone **wants** to implement it.

**Comment by alastair-todd** [comment]
Stumbled here because I want to specify unique keys. Totally concur with @joaomcarlos 

We've had to implement custom code validators for simple things like comparing two dates (even when they are expressed as an integer). It can't be done "native". Now this is not a complete validation model that I can send to customers, like I could an xsd...

Now I'm really stuck between the devil and the deep blue sea.

**Comment by pmsreenivas** [comment]
I can think of two scenarios when it comes to uniqueness of multiple keys -

Scenario 1 - similar to @chapmanjw (Dec 9, 2019), the composite combination of key1 and key2 must be unique. As in, two or more objects in the array can have the same key1 or same key2, but no two objects can have the same key1 + key2 combination.

```
{
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
                "key1": { "type": "string" },
                "key2": { "type": "string" },
                "value": { "type": "integer" }
            }
        },
        "compositeUniquenessKeys": [ "#/key1", "#/key2" ]
    }
```
Example pass case :- 

Multiple objects have the same key1/key2 but no two objects have the same key1 + key2 combination

```
[
        {
            "key1": "abc",
            "key2": "pqr",
            "value": 14
        },
        {
            "key1": "abc2",
            "key2": "pqr",
            "value": 10
        },
        {
            "key1": "abc",
            "key2": "pqr2",
            "value": 10
        }
    ]
```

Example fail case :- 

First two objects have same key1 + key2 combination

```
[
        {
            "key1": "abc",
            "key2": "pqr",
            "value": 10
        },
        {
            "key1": "abc",
            "key2": "pqr",
            "value": 13
        },
        {
            "key1": "abc",
            "key2": "pqr2",
            "value": 10
        }
    ]
```

Scenario 2 - Objects within the array should not have the same value for key 1 or key 2 (can be extended for as many keys as possible)

```
{
        "type": "array",
        "items": {
            "type": "object",
            "properties": {
                "key1": { "type": "string" },
                "key2": { "type": "string" },
                "value": { "type": "integer" }
            }
        },
        "nonCompositeUniquenessKeys": [ "#/key1", "#/key2" ]
    }
```
Example pass case :-

Both key1 and key2 are unique across all three objects

```
[
        {
            "key1": "abc",
            "key2": "pqr",
            "value": 10
        },
        {
            "key1": "abc2",
            "key2": "pqr2",
            "value": 9
        },
        {
            "key1": "abc3",
            "key2": "pqr3",
            "value": 10
        }
    ]
```

Example fail case :- 

Although key1 is unique across all three objects, key2 is not. We don't care about the key1 + key2 combination here

```
[
        {
            "key1": "abc",
            "key2": "pqr",
            "value": 10
        },
        {
            "key1": "abc2",
            "key2": "pqr",
            "value": 10
        },
        {
            "key1": "abc3",
            "key2": "pqr2",
            "value": 10
        }
    ]
```
These examples can be extended to have more than two keys.

I would like to have both these scenarios included as features.

**Comment by pongstylin** [comment]
I was about to make a comment similar to @pmsreenivas.  Multiple keys would be quite useful - composite or not.  My example involves authoring multiple-choice questions.  Authoring test questions is pretty common in the education industry.  Once such a question is authored, it is posted to the server.  The route on the server validates the posted JSON and it would be nice if I can declare and validate the unique keys.  Here's a simplified version of my schema and with a suggestion on how to do so.

```
{
  type: 'object',
  properties: {
    prompt: { type:'string' },
    choices: {
      type: 'array',
      minItems: 2,
      items: {
        type: 'object',
        properties: {
           id: { type:'string', format:'uuid' },
           text: { type:'string' },
        },
        required: [ 'id', 'text' ],
        additionalProperties: false,
      },
      uniqueItems: [
        { key:'id' },
        { key:'text' },
        { key:[ 'composite', 'example' ] }
      ]
    },
    multiple: { type:'boolean' },
  },
  required: [ 'prompt', 'choices', 'multiple' ],
  additionalProperties: false,
}
```

Rationale
- Overloading "uniqueItems" is consistent with how "additionalProperties" are overloaded.  Rather than providing "true", you can define how the items must be unique.
- This does not significantly increase complexity, e.g. by using relative pointers.  But it also does not reduce complexity for uniqueness checks.  The comparison algorithm used to compare unique items today must still be used to compare key values.  This makes it acceptable for a key to have an object value - the objects must be deeply equal.
- Performance should not be a concern.  Testing if two values are deeply equal is a common operation.  Whether you perform this operation during schema validation or move that responsibility elsewhere, the cost remains roughly the same after sufficient optimization - especially for languages such as JavaScript/NodeJS, which are not strongly typed.
- The one downside of this solution is that it avoided pointers in the name of simplicity.  This means we can't assess item uniqueness based on nested keys, which may be required by edge cases I haven't thought of.  But since "uniqueItems" accepts an object (or array of objects) it is extensible.  If you wish to define "pointer" as an alternative to "key" at a later date, then this would be easy.

**Comment by gregsdennis** [comment]
I like the array form for multiple keys, but I'm not sure about the objects with a single `key` property. I think it's simpler just having an array of strings containing pointers.  (I'm not sure what you're trying to do with the "composite" example.)

Pointers don't add to complexity because and validator is already going to know how to resolve them from having to support `$ref`, _et. al._

It's easier to validate at the meta-schema level, too.

As you mentioned, performance isn't a concern. Rather it should be improved since the validator is only required to compare a small number of values rather than an entire tree.

**Comment by pongstylin** [comment]
@gregsdennis 
> I like the array form for multiple keys, but I'm not sure about the objects with a single `key` property. I think it's simpler just having an array of strings containing pointers. (I'm not sure what you're trying to do with the "composite" example.)

Understanding the composite example is essential to understanding my suggestion.  By "composite", I am saying a key composed of multiple parts.  Using my example, this simple line of code should explain it.  So, if you wanted to avoid saying the word "key", we would have to have nested arrays, which is not as easy-to-read.
```
isDuplicate = a.id === b.id || a.text === b.text || (a.composite === b.composite && a.example === b.example)
```

An array of objects (or a single object) is really not that bad.  Seeing the word "key" helps the reader understand what they are looking at.  Also, we may consider adding other parameters to tune object comparisons such as "deep" or "exclude" (these are just examples, not an advocation of adding such parameters).

> Pointers don't add to complexity because and validator is already going to know how to resolve them from having to support `$ref`, _et. al._

If there is no roadblock to using pointers, I'm just as happy to use pointers.  But I wouldn't want pointers to hold up the feature in general.  So I'm pointing out that we could go either way and pivot later.

> As you mentioned, performance isn't a concern. Rather it should be improved since the validator is only required to compare a small number of values rather than an entire tree.

Exactly right.  Specifying unique keys does not reduce complexity, but does improve performance.

**Comment by gregsdennis** [comment]
Oh, you mean that the array items are OR'd together.  I'm not sure I agree with that.  I'm thinking that each item in the array adds to the composite key (they're AND'd).

I'm not certain there's much of a use case for complex boolean login on deciding a uniqueness key.  But to say that `(a.foo, a.bar)` must be unique for any `a` in the array is quite useful.  This is actually the more common pattern, e.g. in document databases (hash and sort keys).

**Comment by pongstylin** [comment]
@gregsdennis I provided a use case where I want multiple fields to be unique - the id as well as the text of a choice in a multiple choice question.  And, when working with databases, I have seen many tables that would have both a unique identifier and some textual representation of the item (e.g. title or name) that should be unique as well - otherwise it would cause a user to be confused seeing an apparent duplicate in a list.  There are exceptions of course for more complex entities where the display text does not need to be unique when other metadata can appear along-side a title or name to distinguish it.  There are other people in this thread that has asked for the same, so I don't think it is that obscure of a need.  But I am glad my code example cleared up my intent.

**Comment by pmsreenivas** [comment]
> Oh, you mean that the array items are OR'd together. I'm not sure I agree with that. I'm thinking that each item in the array adds to the composite key (they're AND'd).
> 
> I'm not certain there's much of a use case for complex boolean login on deciding a uniqueness key. But to say that `(a.foo, a.bar)` must be unique for any `a` in the array is quite useful. This is actually the more common pattern, e.g. in document databases (hash and sort keys).

@gregsdennis 

Based on my comment I posted on Feb 1, 2021 - The Array items must be OR'd if the keys are not composite and independently unique (scenario 2 in my earlier comment) while they must be AND'd if the keys are compositely unique (scenario 1 in my earlier comment)

**Comment by pongstylin** [comment]
I just discovered that multiple unique keys (OR'd) are supported by ajv.
https://github.com/ajv-validator/ajv-keywords#uniqueitemproperties

That basically provides exactly what I need.  Unfortunately, it doesn't support composite keys (AND'd).  But, if your json-schema validator supports custom keywords (like ajv), then here's some code I've been playing with that is a proof-of-concept.  Feel free to use / port it to implement your own uniqueItems keyword.
https://jsbench.me/bckm6l0k0k/1

**Comment by gregsdennis** [comment]
I've created a draft vocab for this.  It can be reviewed [here](https://github.com/gregsdennis/json-everything/pull/120).

This vocab adds the `uniqueKeys` keyword which is an array of JSON Pointers.  Each pointer is applied to each item in an array to produce a set of values for that item.  If one of the pointers can't be resolved it's skipped.

The keyword passes if all of the resulting value sets are unique.

**Comment by gregsdennis** [comment]
I've released the [vocabulary](https://gregsdennis.github.io/json-everything/usage/vocabs-unique-keys.html) and an [implementation](https://www.nuget.org/packages/JsonSchema.Net.UniqueKeys/) for my validator JsonSchema.Net.

**Comment by dudicoco** [comment]
@gregsdennis I can't get `uniqueKeys` to work. 
I tried it with draft 7, draft 2019-09, draft 2020-09 and with https://gregsdennis.github.io/json-everything/meta/unique-keys

I'm not sure if i'm missing something or if the issue is with the validator which i'm using: https://github.com/sirosen/check-jsonschema

**Comment by gregsdennis** [comment]
@dudicoco because this is an externally defined vocabulary, the implementation you're using needs to support it.  If it supports custom keywords, you may be able to add it yourself.  As of right now, my validator is the only one I know of that supports this vocabulary.

There's a lot of discussion in various issues around the difference between vocabularies and their meta-schemas (if they have one).  The meta-schema can provide syntax checking (is the keyword's usage syntactically correct?), but the meta-schema can't define the logic behind the keyword.  I also cover this in a bit more detail in [my docs](https://gregsdennis.github.io/json-everything/usage/schema-vocabs.html).

What you'll need to do is check to see if the validator you're using supports custom keywords and possibly implement it yourself.

If you want to play with it a bit to see if your schema's doing what you expect, you can use https://json-everything.net/json-schema, which is powered by my library and supports my custom vocabularies.

**Comment by dudicoco** [comment]
Thanks @gregsdennis!

Is it possible to define all keys as unique by default?

See the following schema snippet for example:
```json
            "environment_variables": {
              "type": "object",
              "required": [],
              "patternProperties": {
                "(^([a-z]+[.])+[a-z_]+)$|(^([A-Z0-9_])+([A-Z0-9_]?)+([A-Z0-9])+)$": {
                  "type": [
                    "string"
                  ]
                }
              },
              "additionalProperties": false
            }
```

In this case we can't specify each key in `uniqueKeys` as the key names are not fixed.

**Comment by gregsdennis** [comment]
Hey @dudicoco. Please raise the issue over in my repo https://github.com/gregsdennis/json-everything.  Happy to discuss your needs there.

**Comment by mprevdelta** [comment]
Reading all this just reinforces for me that anyone doing document databases should have it impressed upon them that only very simple, fundamental objects should be nested. If you have a document containing an array of unique objects, break out a collection and store that as an array of ids to the new collection objects instead.

The tools will allow you to make nested objects that look like they should work, and even do some pretty advanced operations on them, but when you get to adding indexes and constraints or doing reporting, it all falls apart.

**Comment by dudicoco** [comment]
@mprevdelta can you share an example?

**Comment by amannm** [comment]
This feature is similar to `x-kubernetes-patch-merge-key` ... would be useful to make standard JSON schema arrays patchable with a similar "strategic merge" that Kubernetes does on fields with those property extensions

**Comment by MT-0** [comment]
@gregsdennis 

> Oh, you mean that the array items are OR'd together. I'm not sure I agree with that. I'm thinking that each item in the array adds to the composite key (they're AND'd).
> 
> I'm not certain there's much of a use case for complex boolean login on deciding a uniqueness key. But to say that `(a.foo, a.bar)` must be unique for any `a` in the array is quite useful. This is actually the more common pattern, e.g. in document databases (hash and sort keys).

Defining an array of keys to automatically describe a composite key is not useful as it prevents defining multiple unique keys.

```
uniqueKeys: [ "/key1", "/key2" ]
```

Could either be defined as either:

1. The `key1` property is unique and independently the `key2` property is unique; or
2. The tuple `key1`, `key2` is unique.

If you define it as option 1 then the vocabulary can be extended such that `uniqueKeys` could take an array of arrays:

```
uniqueKeys: [ ["/key1"], ["/key2"], ["/key3", "/key4"] ]
```

Such that `key1` is unique, independently `key2` is unique, and again independently the tuple `key3` and `key4` is unique.

There may be a case to allow a simplified version of the syntax such that if a nested array contains only a single item then it could be rewritten without the array wrapper so that the previous example would be functionally identical to:

```
uniqueKeys: [ "/key1", "/key2", ["/key3", "/key4"] ]
```

This would be particularly useful for JSON:API resources where you would quite often want something like, for example, for an employee where they have a unique id, a unique username and a unique combination of several other fields:

```
uniqueKeys: [
  ["/id"],
  ["/attributes/username"],
  ["/references/team/data/id", "/attributes/index-within-team"]
]
```

**Comment by gregsdennis** [comment]
@MT-0 what you're describing can be done with my proposal (and what's currently described in the [vocab](https://docs.json-everything.net/schema/vocabs/uniquekeys/) I wrote).  You just need an `allOf`.

```jsonc
{
  // ...
  "allOf": [
    { "uniqueKeys": [ "/key1" ] },
    { "uniqueKeys": [ "/key2" ] },
    { "uniqueKeys": [ "/key3", "/key4" ] }
  ]
}
```

It's more verbose, but it's also more explicit and easier to read.
